# Generated by Django 4.0.1 on 2022-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
